export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const GET_INDICATOR_MESSAGES = 'GET_INDICATOR_MESSAGES';
export const FETCH_INDICATOR_MESSAGES_FAILED = 'FETCH_INDICATOR_MESSAGES_FAILED';
export const INDICATOR_MESSAGES_START = 'INDICATOR_MESSAGES_START';
export const GET_INDICATOR_MESSAGE_DETAILS = 'GET_INDICATOR_MESSAGE_DETAILS';
export const FETCH_INDICATOR_MESSAGE_DETAILS_FAILED = 'FETCH_INDICATOR_MESSAGE_DETAILS_FAILED';